name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker for gcloud
        run: gcloud auth configure-docker

      - name: Debug GCP_PROJECT_ID and Docker Tag
        run: |
          echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}"
          echo "Docker Tag: gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:latest"

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:latest \
            --push .
